### ISSUE TITLE
Why is this package not registered?

### ISSUE THREAD

**Issue by findmyway** [StefanKarpinski/Cards.jl#7]

**Comment by StefanKarpinski** [comment]
Two reasons: I don't really intend to maintain it and it doesn't feel complete enough for a release. If someone else wants to do something real with it and maintain it, the code is MIT-licensed, so they're welcome to do so.

**Comment by findmyway** [comment]
Thanks for your explanation. I'm working on some card games and may enrich this package at some point later.

**Comment by StefanKarpinski** [comment]
Sounds good! Feel free to make a pull request here and if this package gets to the point where it's complete enough to be registered, we can register it and maybe even transfer it to an appropriate organization.
